=== carla-simulator/carla/PythonAPI/carla/data/xsd/edges_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="baseTypes.xsd"/>

    <xsd:element name="edges" type="edgesType">
        <xsd:key name="edgeKey">
            <xsd:selector xpath="edge"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
    </xsd:element>

    <xsd:complexType name="edgesType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="edge" type="edgeType"/>
            <xsd:element name="roundabout" type="roundaboutType"/>
            <xsd:element name="delete" type="deleteType"/>
        </xsd:choice>
        <xsd:attribute name="version" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d+.\d+"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="edgeType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="lane" type="laneType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="split" type="splitType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="neigh" type="neighType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="from" type="xsd:string" use="required"/>
        <xsd:attribute name="to" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="length" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="bidi" type="xsd:string" use="optional"/>
        <xsd:attribute name="endOffset" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="numLanes" type="xsd:positiveInteger" use="optional"/>
        <xsd:attribute name="speed" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="priority" type="xsd:int" use="optional"/>
        <xsd:attribute name="width" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="sidewalkWidth" type="nonNegativeFloatType"/>
        <xsd:attribute name="bikeLaneWidth" type="nonNegativeFloatType"/>
        <xsd:attribute name="distance" type="xsd:float"/>
        <xsd:attribute name="spreadType" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="center"/>
                    <xsd:enumeration value="roadCenter"/>
                    <xsd:enumeration value="right"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="laneType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="neigh" type="neighType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="speed" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="width" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="prefer" type="xsd:string" use="optional"/>
        <xsd:attribute name="acceleration" type="boolType" use="optional"/>
        <xsd:attribute name="endOffset" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="deleteType">
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="roundaboutType">
        <xsd:attribute name="nodes" type="xsd:string" use="optional"/>
        <xsd:attribute name="edges" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="neighType">
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="stopOffsetType">
        <xsd:attribute name="value" type="nonNegativeFloatType" use="required"/>
        <xsd:attribute name="exceptions" type="xsd:string" use="optional"/>
        <xsd:attribute name="vClasses" type="xsd:string" use="optional"/>
    </xsd:complexType>

</xsd:schema>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/examples/netconvert/types/cross_usingtypes/input_edges.edg.xml
<edges xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/edges_file.xsd">
   <edge id="1fi" from="1" to="m1" type="b"/>
   <edge id="1si" from="m1" to="0" type="a"/>
   <edge id="1o" from="0" to="1" type="c"/>

   <edge id="2fi" from="2" to="m2" type="b"/>
   <edge id="2si" from="m2" to="0" type="a"/>
   <edge id="2o" from="0" to="2" type="c"/>

   <edge id="3fi" from="3" to="m3" type="b"/>
   <edge id="3si" from="m3" to="0" type="a"/>
   <edge id="3o" from="0" to="3" type="c"/>

   <edge id="4fi" from="4" to="m4" type="b"/>
   <edge id="4si" from="m4" to="0" type="a"/>
   <edge id="4o" from="0" to="4" type="c"/>

</edges>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/examples/netconvert/speed_in_kmh/cross_notypes_kmh/input_edges.edg.xml
<edges xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/edges_file.xsd">
   <edge id="1fi" from="1" to="m1" priority="2" numLanes="2" speed="40" />
   <edge id="1si" from="m1" to="0" priority="3" numLanes="3" speed="50" />
   <edge id="1o" from="0" to="1" priority="1" numLanes="1" speed="40" />

   <edge id="2fi" from="2" to="m2" priority="2" numLanes="2" speed="40" />
   <edge id="2si" from="m2" to="0" priority="3" numLanes="3" speed="50" />
   <edge id="2o" from="0" to="2" priority="1" numLanes="1" speed="40" />

   <edge id="3fi" from="3" to="m3" priority="2" numLanes="2" speed="40" />
   <edge id="3si" from="m3" to="0" priority="3" numLanes="3" speed="50" />
   <edge id="3o" from="0" to="3" priority="1" numLanes="1" speed="40" />

   <edge id="4fi" from="4" to="m4" priority="2" numLanes="2" speed="40" />
   <edge id="4si" from="m4" to="0" priority="3" numLanes="3" speed="50" />
   <edge id="4o" from="0" to="4" priority="1" numLanes="1" speed="40" />

</edges>
