=== carla-simulator/carla/PythonAPI/carla/data/xsd/net_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="taz_file.xsd" />

    <xsd:element name="net" type="netType">
        <xsd:key name="edgeKey">
            <xsd:selector xpath="edge"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
        <xsd:keyref name="edgeKeyRefFrom" refer="edgeKey">
            <xsd:selector xpath="connection"/>
            <xsd:field xpath="@from"/>
        </xsd:keyref>
        <xsd:keyref name="edgeKeyRefTo" refer="edgeKey">
            <xsd:selector xpath="connection"/>
            <xsd:field xpath="@to"/>
        </xsd:keyref>
    </xsd:element>

    <xsd:complexType name="netType">
        <xsd:sequence>
            <xsd:element name="location" type="locationType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="edge" type="edgeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="tlLogic" type="tlLogicType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="junction" type="junctionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="connection" type="connectionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="prohibition" type="prohibitionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="roundabout" type="roundaboutType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="taz" type="tazType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="version">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d+.\d+"></xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="junctionCornerDetail" type="xsd:int"/>
        <xsd:attribute name="junctionLinkDetail" type="xsd:int"/>
        <xsd:attribute name="lefthand" type="boolType"/>
        <xsd:attribute name="rectangularLaneCut" type="boolType"/>
        <xsd:attribute name="walkingareas" type="boolType"/>
        <xsd:attribute name="limitTurnSpeed" type="xsd:float"/>
        <xsd:attribute name="checkLaneFoesAll" type="boolType"/>
        <xsd:attribute name="checkLaneFoesRoundabout" type="boolType"/>
        <xsd:attribute name="tlsIgnoreInternalJunctionJam" type="boolType"/>
        <xsd:attribute name="spreadType" type="spreadTypeType"/>
        <xsd:attribute name="avoidOverlap" type="boolType"/>
    </xsd:complexType>

    <xsd:complexType name="edgeType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="lane" type="laneType" minOccurs="1" maxOccurs="63"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="function" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="normal"/>
                    <xsd:enumeration value="internal"/>
                    <xsd:enumeration value="connector"/>
                    <xsd:enumeration value="crossing"/>
                    <xsd:enumeration value="walkingarea"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="from" type="xsd:string"/>
        <xsd:attribute name="to" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="priority" type="xsd:integer" use="optional"/>
        <xsd:attribute name="length" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="bidi" type="xsd:string" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="shape" type="shapeTypeTwo" use="optional"/>
        <xsd:attribute name="distance" type="xsd:float"/>
        <xsd:attribute name="spreadType" type="spreadTypeType" use="optional"/>
        <xsd:attribute name="crossingEdges" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:simpleType name="spreadTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="center"/>
            <xsd:enumeration value="roadCenter"/>
            <xsd:enumeration value="right"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="laneType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="neigh" type="neighType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="prefer" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="positiveFloatType" use="required"/>
        <xsd:attribute name="length" type="positiveFloatType" use="required"/>
        <xsd:attribute name="endOffset" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="width" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="acceleration" type="boolType" use="optional"/>
        <xsd:attribute name="shape" type="shapeTypeTwo" use="required"/>
        <xsd:attribute name="customShape" type="boolType" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="junctionType">
        <xsd:sequence>
            <xsd:element name="request" type="requestType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="x" type="xsd:float" use="required"/>
        <xsd:attribute name="y" type="xsd:float" use="required"/>
        <xsd:attribute name="z" type="xsd:float" use="optional"/>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="traffic_light"/>
                    <xsd:enumeration value="traffic_light_unregulated"/>
                    <xsd:enumeration value="traffic_light_right_on_red"/>
                    <xsd:enumeration value="rail_signal"/>
                    <xsd:enumeration value="rail_crossing"/>
                    <xsd:enumeration value="priority"/>
                    <xsd:enumeration value="priority_stop"/>
                    <xsd:enumeration value="right_before_left"/>
                    <xsd:enumeration value="allway_stop"/>
                    <xsd:enumeration value="zipper"/>
                    <xsd:enumeration value="district"/>
                    <xsd:enumeration value="unregulated"/>
                    <xsd:enumeration value="internal"/>
                    <xsd:enumeration value="dead_end"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="incLanes" type="xsd:string" use="required"/>
        <xsd:attribute name="intLanes" type="xsd:string" use="required"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="radius" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="customShape" type="boolType" use="optional"/>
        <xsd:attribute name="rightOfWay" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="edgePriority"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="fringe" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="outer"/>
                    <xsd:enumeration value="inner"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="requestType">
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="response" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="foes" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="cont" type="boolType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="stopOffsetType">
        <xsd:attribute name="value" type="nonNegativeFloatType" use="required"/>
        <xsd:attribute name="vClasses" type="xsd:string" use="optional"/>
        <xsd:attribute name="exceptions" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="connectionType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="from" type="xsd:string" use="required"/>
        <xsd:attribute name="to" type="xsd:string" use="required"/>
        <xsd:attribute name="fromLane" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="toLane" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="pass" type="boolType" use="optional"/>
        <xsd:attribute name="keepClear" type="boolType" use="optional"/>
        <xsd:attribute name="contPos" type="xsd:float" use="optional"/>
        <xsd:attribute name="visibility" type="xsd:float" use="optional"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="xsd:float" use="optional"/>
        <xsd:attribute name="length" type="xsd:float" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="uncontrolled" type="boolType" use="optional"/>
        <xsd:attribute name="via" type="xsd:string" use="optional"/>
        <xsd:attribute name="tl" type="xsd:string" use="optional"/>
        <xsd:attribute name="linkIndex" type="xsd:integer" use="optional"/>
        <xsd:attribute name="linkIndex2" type="xsd:integer" use="optional"/>
        <xsd:attribute name="dir" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="s"/>
                    <xsd:enumeration value="t"/>
                    <xsd:enumeration value="T"/>
                    <xsd:enumeration value="l"/>
                    <xsd:enumeration value="r"/>
                    <xsd:enumeration value="L"/>
                    <xsd:enumeration value="R"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="state" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="M"/>
                    <xsd:enumeration value="m"/>
                    <xsd:enumeration value="O"/>
                    <xsd:enumeration value="o"/>
                    <xsd:enumeration value="="/>
                    <xsd:enumeration value="-"/>
                    <xsd:enumeration value="s"/>
                    <xsd:enumeration value="w"/>
                    <xsd:enumeration value="Z"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="prohibitionType">
        <xsd:attribute name="prohibitor" type="xsd:string" use="required"/>
        <xsd:attribute name="prohibited" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="roundaboutType">
        <xsd:attribute name="nodes" type="xsd:string" use="required"/>
        <xsd:attribute name="edges" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="neighType">
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/examples/sumo/model_railroad/motorway.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu May  2 22:28:17 2019 by Eclipse SUMO netconvert Version v1_2_0+0149-6b40db9d1b
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <node-files value="motorway.nod.xml"/>
        <edge-files value="motorway.edg.xml"/>
        <connection-files value="motorway.con.xml"/>
    </input>

    <output>
        <output-file value="motorway.net.xml"/>
    </output>

    <processing>
        <offset.disable-normalization value="true"/>
    </processing>

</configuration>
-->

<net version="1.3" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="0.00,0.00" convBoundary="-6000.00,-50.00,3500.00,1.60" origBoundary="-6000.00,-50.00,3500.00,1.60" projParameter="!"/>

    <edge id=":B_0" function="internal">
        <lane id=":B_0_0" index="0" speed="36.00" length="8.00" shape="-3004.00,-1.60 -2996.00,-1.60"/>
        <lane id=":B_0_1" index="1" speed="36.00" length="8.00" shape="-3004.00,1.60 -2996.00,1.60"/>
    </edge>
    <edge id=":C_0" function="internal">
        <lane id=":C_0_0" index="0" speed="36.00" length="8.00" shape="-4.00,-1.60 4.00,-1.60"/>
        <lane id=":C_0_1" index="1" speed="36.00" length="8.00" shape="-4.00,1.60 4.00,1.60"/>
    </edge>
    <edge id=":C_2" function="internal">
        <lane id=":C_2_0" index="0" speed="36.00" length="8.00" shape="-4.00,-5.00 4.00,-4.80"/>
    </edge>
    <edge id=":D_0" function="internal">
        <lane id=":D_0_0" index="0" speed="36.00" length="8.00" shape="96.00,-4.80 104.00,-5.00"/>
    </edge>
    <edge id=":D_1" function="internal">
        <lane id=":D_1_0" index="0" speed="36.00" length="8.00" shape="96.00,-1.60 104.00,-1.60"/>
        <lane id=":D_1_1" index="1" speed="36.00" length="8.00" shape="96.00,1.60 104.00,1.60"/>
    </edge>
    <edge id=":E_0" function="internal">
        <lane id=":E_0_0" index="0" speed="36.00" length="8.21" shape="296.00,-1.60 298.40,-1.35 300.00,-0.80 301.60,-0.25 304.00,0.00"/>
    </edge>
    <edge id=":F_0" function="internal">
        <lane id=":F_0_0" index="0" speed="36.00" length="0.10" shape="3300.00,0.00 3300.00,0.00"/>
    </edge>

    <edge id="beg" from="A" to="B" priority="-1" spreadType="center" shape="-6000.00,1.60 -3000.00,1.60" distance="10000.00">
        <lane id="beg_0" index="0" speed="36.00" length="2996.00" shape="-6000.00,-1.60 -3004.00,-1.60"/>
        <lane id="beg_1" index="1" speed="36.00" length="2996.00" shape="-6000.00,1.60 -3004.00,1.60"/>
        <lane id="beg_2" index="2" speed="36.00" length="2996.00" shape="-6000.00,4.80 -3004.00,4.80"/>
    </edge>
    <edge id="beg2" from="B" to="C" priority="-1" spreadType="center" distance="13004.00">
        <lane id="beg2_0" index="0" speed="36.00" length="2992.00" shape="-2996.00,-1.60 -4.00,-1.60"/>
        <lane id="beg2_1" index="1" speed="36.00" length="2992.00" shape="-2996.00,1.60 -4.00,1.60"/>
    </edge>
    <edge id="end" from="D" to="E" priority="-1" spreadType="center" distance="16104.00">
        <lane id="end_0" index="0" speed="36.00" length="192.00" shape="104.00,-1.60 296.00,-1.60"/>
        <lane id="end_1" index="1" speed="36.00" length="192.00" shape="104.00,1.60 296.00,1.60"/>
    </edge>
    <edge id="end2" from="E" to="F" priority="-1" spreadType="center" distance="16304.00">
        <lane id="end2_0" index="0" speed="36.00" length="2996.00" shape="304.00,0.00 3300.00,0.00"/>
    </edge>
    <edge id="end3" from="F" to="G" priority="-1" spreadType="center" distance="19300.00">
        <lane id="end3_0" index="0" speed="36.00" length="200.00" shape="3300.00,0.00 3500.00,0.00"/>
    </edge>
    <edge id="merge" from="C" to="D" priority="-1" spreadType="center" shape="0.00,-1.60 100.00,-1.60" distance="16004.00">
        <lane id="merge_0" index="0" speed="36.00" length="92.00" acceleration="1" shape="4.00,-4.80 96.00,-4.80"/>
        <lane id="merge_1" index="1" speed="36.00" length="92.00" shape="4.00,-1.60 96.00,-1.60"/>
        <lane id="merge_2" index="2" speed="36.00" length="92.00" shape="4.00,1.60 96.00,1.60"/>
    </edge>
    <edge id="offRamp" from="D" to="offRampEnd" priority="-1" spreadType="center" shape="100.00,-5.00 150.00,-5.00 300.00,-50.00">
        <lane id="offRamp_0" index="0" speed="36.00" length="202.60" shape="104.00,-5.00 150.00,-5.00 300.00,-50.00"/>
    </edge>
    <edge id="onRamp" from="onRampBeg" to="C" priority="-1" spreadType="center" shape="-300.00,-50.00 -30.00,-5.00 0.00,-5.00">
        <lane id="onRamp_0" index="0" speed="36.00" length="299.72" shape="-300.00,-50.00 -30.00,-5.00 -4.00,-5.00"/>
    </edge>

    <junction id="A" type="dead_end" x="-6000.00" y="0.00" incLanes="" intLanes="" shape="-6000.00,6.40 -6000.00,-3.20"/>
    <junction id="B" type="unregulated" x="-3000.00" y="0.00" incLanes="beg_0 beg_1 beg_2" intLanes=":B_0_0 :B_0_1" shape="-2996.00,3.20 -2996.00,-3.20 -3004.00,-3.20 -3004.00,6.40 -3000.97,5.57 -2999.03,4.03 -2997.79,3.44"/>
    <junction id="C" type="priority" x="0.00" y="0.00" incLanes="beg2_0 beg2_1 onRamp_0" intLanes=":C_0_0 :C_0_1 :C_2_0" shape="4.00,3.20 4.00,-6.40 -4.00,-6.60 -4.00,3.20">
        <request index="0" response="000" foes="000" cont="0"/>
        <request index="1" response="000" foes="000" cont="0"/>
        <request index="2" response="000" foes="000" cont="0"/>
    </junction>
    <junction id="D" type="priority" x="100.00" y="0.00" incLanes="merge_0 merge_1 merge_2" intLanes=":D_0_0 :D_1_0 :D_1_1" shape="104.00,3.20 104.00,-6.60 96.00,-6.40 96.00,3.20">
        <request index="0" response="000" foes="000" cont="0"/>
        <request index="1" response="000" foes="000" cont="0"/>
        <request index="2" response="000" foes="000" cont="0"/>
    </junction>
    <junction id="E" type="unregulated" x="300.00" y="0.00" incLanes="end_0 end_1" intLanes=":E_0_0" shape="304.00,1.60 304.00,-1.60 301.02,-2.01 298.98,-2.79 297.73,-3.08 296.00,-3.20 296.00,3.20 298.98,2.79 301.02,2.01 302.27,1.72"/>
    <junction id="F" type="unregulated" x="3300.00" y="0.00" incLanes="end2_0" intLanes=":F_0_0" shape="3300.00,1.60 3300.00,-1.60 3300.00,1.60"/>
    <junction id="G" type="dead_end" x="3500.00" y="0.00" incLanes="end3_0" intLanes="" shape="3500.00,-1.60 3500.00,1.60"/>
    <junction id="offRampEnd" type="dead_end" x="300.00" y="-50.00" incLanes="offRamp_0" intLanes="" shape="299.54,-51.53 300.46,-48.47"/>
    <junction id="onRampBeg" type="dead_end" x="-300.00" y="-50.00" incLanes="" intLanes="" shape="-300.26,-48.42 -299.74,-51.58"/>

    <connection from="beg" to="beg2" fromLane="0" toLane="0" via=":B_0_0" dir="s" state="M"/>
    <connection from="beg" to="beg2" fromLane="1" toLane="1" via=":B_0_1" dir="s" state="M"/>
    <connection from="beg2" to="merge" fromLane="0" toLane="1" pass="1" via=":C_0_0" dir="s" state="M"/>
    <connection from="beg2" to="merge" fromLane="1" toLane="2" pass="1" via=":C_0_1" dir="s" state="M"/>
    <connection from="end" to="end2" fromLane="0" toLane="0" via=":E_0_0" dir="s" state="M"/>
    <connection from="end2" to="end3" fromLane="0" toLane="0" via=":F_0_0" dir="s" state="M"/>
    <connection from="merge" to="offRamp" fromLane="0" toLane="0" pass="1" via=":D_0_0" dir="s" state="M"/>
    <connection from="merge" to="end" fromLane="1" toLane="0" pass="1" via=":D_1_0" dir="s" state="M"/>
    <connection from="merge" to="end" fromLane="2" toLane="1" pass="1" via=":D_1_1" dir="s" state="M"/>
    <connection from="onRamp" to="merge" fromLane="0" toLane="0" pass="1" via=":C_2_0" dir="s" state="M"/>

    <connection from=":B_0" to="beg2" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":B_0" to="beg2" fromLane="1" toLane="1" dir="s" state="M"/>
    <connection from=":C_0" to="merge" fromLane="0" toLane="1" dir="s" state="M"/>
    <connection from=":C_0" to="merge" fromLane="1" toLane="2" dir="s" state="M"/>
    <connection from=":C_2" to="merge" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":D_0" to="offRamp" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":D_1" to="end" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":D_1" to="end" fromLane="1" toLane="1" dir="s" state="M"/>
    <connection from=":E_0" to="end2" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":F_0" to="end3" fromLane="0" toLane="0" dir="s" state="M"/>

</net>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/examples/sumo/model_railroad/three_split.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Tue Nov  4 23:07:07 2014 by SUMO netconvert Version dev-SVN-r17257
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <node-files value="./sumo/three_split.nod.xml"/>
        <edge-files value="./sumo/three_split.edg.xml"/>
    </input>

    <output>
        <output-file value="./sumo/three_split.net.xml"/>
    </output>

    <processing>
        <no-internal-links value="true"/>
    </processing>

    <report>
        <verbose value="true"/>
    </report>

</configuration>
-->

<net version="0.13" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="0.00,500.00" convBoundary="0.00,0.00,2500.00,1000.00" origBoundary="0.00,-500.00,2500.00,500.00" projParameter="!"/>

    <edge id="beg" from="absBeg" to="beg" priority="-1">
        <lane id="beg_0" index="0" speed="27.80" length="500.00" shape="0.00,498.35 495.25,498.35"/>
    </edge>
    <edge id="beg2left" from="beg" to="begleft" priority="-1">
        <lane id="beg2left_0" index="0" speed="13.90" length="503.09" shape="501.65,501.45 501.65,996.75"/>
    </edge>
    <edge id="beg2right" from="beg" to="begright" priority="-1">
        <lane id="beg2right_0" index="0" speed="13.90" length="500.00" shape="498.35,495.25 498.35,-0.05"/>
    </edge>
    <edge id="end" from="end" to="absEnd" priority="-1">
        <lane id="end_0" index="0" speed="27.80" length="500.00" shape="1504.75,498.35 2000.00,498.35"/>
    </edge>
    <edge id="left" from="begleft" to="endleft" priority="-1">
        <lane id="left_0" index="0" speed="13.90" length="1006.18" shape="503.25,998.35 1496.75,998.35"/>
    </edge>
    <edge id="left2end" from="endleft" to="end" priority="-1">
        <lane id="left2end_0" index="0" speed="13.90" length="503.09" shape="1498.35,996.75 1498.35,501.45"/>
    </edge>
    <edge id="middle" from="beg" to="end" priority="-1">
        <lane id="middle_0" index="0" speed="27.80" length="1000.00" shape="504.75,498.35 1495.25,498.35"/>
    </edge>
    <edge id="rend" from="absEnd" to="rabsEnd" priority="-1">
        <lane id="rend_0" index="0" speed="27.80" length="500.00" shape="2000.00,498.35 2500.00,498.35"/>
    </edge>
    <edge id="right" from="begright" to="endright" priority="-1">
        <lane id="right_0" index="0" speed="13.90" length="1000.00" shape="499.95,-1.65 1500.05,-1.65"/>
    </edge>
    <edge id="right2end" from="endright" to="end" priority="-1">
        <lane id="right2end_0" index="0" speed="13.90" length="500.00" shape="1501.65,-0.05 1501.65,495.25"/>
    </edge>

    <junction id="absBeg" type="unregulated" x="0.00" y="500.00" incLanes="" intLanes="" shape="-0.00,499.95 -0.00,496.75"/>
    <junction id="absEnd" type="priority" x="2000.00" y="500.00" incLanes="end_0" intLanes="" shape="2000.00,499.95 2000.00,496.75 2000.00,499.95">
        <request index="0" response="0" foes="0"/>
    </junction>
    <junction id="beg" type="priority" x="500.00" y="500.00" incLanes="beg_0" intLanes="" shape="500.05,501.45 503.25,501.45 504.75,499.95 504.75,496.75 499.95,495.25 496.75,495.25 495.25,496.75 495.25,499.95">
        <request index="0" response="000" foes="000"/>
        <request index="1" response="000" foes="000"/>
        <request index="2" response="000" foes="000"/>
    </junction>
    <junction id="begleft" type="priority" x="500.00" y="1000.00" incLanes="beg2left_0" intLanes="" shape="503.25,999.95 503.25,996.75 500.05,996.75">
        <request index="0" response="0" foes="0"/>
    </junction>
    <junction id="begright" type="priority" x="500.00" y="0.00" incLanes="beg2right_0" intLanes="" shape="496.75,-0.05 499.95,-0.05 499.95,-3.25">
        <request index="0" response="0" foes="0"/>
    </junction>
    <junction id="end" type="priority" x="1500.00" y="500.00" incLanes="left2end_0 right2end_0 middle_0" intLanes="" shape="1496.75,501.45 1499.95,501.45 1504.75,499.95 1504.75,496.75 1503.25,495.25 1500.05,495.25 1495.25,496.75 1495.25,499.95">
        <request index="0" response="110" foes="110"/>
        <request index="1" response="100" foes="101"/>
        <request index="2" response="000" foes="011"/>
    </junction>
    <junction id="endleft" type="priority" x="1500.00" y="1000.00" incLanes="left_0" intLanes="" shape="1499.95,996.75 1496.75,996.75 1496.75,999.95">
        <request index="0" response="0" foes="0"/>
    </junction>
    <junction id="endright" type="priority" x="1500.00" y="0.00" incLanes="right_0" intLanes="" shape="1500.05,-0.05 1503.25,-0.05 1500.05,-3.25 1500.05,-0.05">
        <request index="0" response="0" foes="0"/>
    </junction>
    <junction id="rabsEnd" type="unregulated" x="2500.00" y="500.00" incLanes="rend_0" intLanes="" shape="2500.00,496.75 2500.00,499.95"/>

    <connection from="beg" to="beg2right" fromLane="0" toLane="0" dir="r" state="M"/>
    <connection from="beg" to="middle" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from="beg" to="beg2left" fromLane="0" toLane="0" dir="l" state="M"/>
    <connection from="beg2left" to="left" fromLane="0" toLane="0" dir="r" state="M"/>
    <connection from="beg2right" to="right" fromLane="0" toLane="0" dir="l" state="M"/>
    <connection from="end" to="rend" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from="left" to="left2end" fromLane="0" toLane="0" dir="r" state="M"/>
    <connection from="left2end" to="end" fromLane="0" toLane="0" dir="l" state="m"/>
    <connection from="middle" to="end" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from="right" to="right2end" fromLane="0" toLane="0" dir="l" state="M"/>
    <connection from="right2end" to="end" fromLane="0" toLane="0" dir="r" state="m"/>

</net>
