=== carla-simulator/carla/PythonAPI/carla/data/xsd/net_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="taz_file.xsd" />

    <xsd:element name="net" type="netType">
        <xsd:key name="edgeKey">
            <xsd:selector xpath="edge"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
        <xsd:keyref name="edgeKeyRefFrom" refer="edgeKey">
            <xsd:selector xpath="connection"/>
            <xsd:field xpath="@from"/>
        </xsd:keyref>
        <xsd:keyref name="edgeKeyRefTo" refer="edgeKey">
            <xsd:selector xpath="connection"/>
            <xsd:field xpath="@to"/>
        </xsd:keyref>
    </xsd:element>

    <xsd:complexType name="netType">
        <xsd:sequence>
            <xsd:element name="location" type="locationType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="edge" type="edgeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="tlLogic" type="tlLogicType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="junction" type="junctionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="connection" type="connectionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="prohibition" type="prohibitionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="roundabout" type="roundaboutType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="taz" type="tazType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="version">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d+.\d+"></xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="junctionCornerDetail" type="xsd:int"/>
        <xsd:attribute name="junctionLinkDetail" type="xsd:int"/>
        <xsd:attribute name="lefthand" type="boolType"/>
        <xsd:attribute name="rectangularLaneCut" type="boolType"/>
        <xsd:attribute name="walkingareas" type="boolType"/>
        <xsd:attribute name="limitTurnSpeed" type="xsd:float"/>
        <xsd:attribute name="checkLaneFoesAll" type="boolType"/>
        <xsd:attribute name="checkLaneFoesRoundabout" type="boolType"/>
        <xsd:attribute name="tlsIgnoreInternalJunctionJam" type="boolType"/>
        <xsd:attribute name="spreadType" type="spreadTypeType"/>
        <xsd:attribute name="avoidOverlap" type="boolType"/>
    </xsd:complexType>

    <xsd:complexType name="edgeType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="lane" type="laneType" minOccurs="1" maxOccurs="63"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="function" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="normal"/>
                    <xsd:enumeration value="internal"/>
                    <xsd:enumeration value="connector"/>
                    <xsd:enumeration value="crossing"/>
                    <xsd:enumeration value="walkingarea"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="from" type="xsd:string"/>
        <xsd:attribute name="to" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="priority" type="xsd:integer" use="optional"/>
        <xsd:attribute name="length" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="bidi" type="xsd:string" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="shape" type="shapeTypeTwo" use="optional"/>
        <xsd:attribute name="distance" type="xsd:float"/>
        <xsd:attribute name="spreadType" type="spreadTypeType" use="optional"/>
        <xsd:attribute name="crossingEdges" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:simpleType name="spreadTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="center"/>
            <xsd:enumeration value="roadCenter"/>
            <xsd:enumeration value="right"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="laneType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="neigh" type="neighType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="prefer" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="positiveFloatType" use="required"/>
        <xsd:attribute name="length" type="positiveFloatType" use="required"/>
        <xsd:attribute name="endOffset" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="width" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="acceleration" type="boolType" use="optional"/>
        <xsd:attribute name="shape" type="shapeTypeTwo" use="required"/>
        <xsd:attribute name="customShape" type="boolType" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="junctionType">
        <xsd:sequence>
            <xsd:element name="request" type="requestType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="x" type="xsd:float" use="required"/>
        <xsd:attribute name="y" type="xsd:float" use="required"/>
        <xsd:attribute name="z" type="xsd:float" use="optional"/>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="traffic_light"/>
                    <xsd:enumeration value="traffic_light_unregulated"/>
                    <xsd:enumeration value="traffic_light_right_on_red"/>
                    <xsd:enumeration value="rail_signal"/>
                    <xsd:enumeration value="rail_crossing"/>
                    <xsd:enumeration value="priority"/>
                    <xsd:enumeration value="priority_stop"/>
                    <xsd:enumeration value="right_before_left"/>
                    <xsd:enumeration value="allway_stop"/>
                    <xsd:enumeration value="zipper"/>
                    <xsd:enumeration value="district"/>
                    <xsd:enumeration value="unregulated"/>
                    <xsd:enumeration value="internal"/>
                    <xsd:enumeration value="dead_end"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="incLanes" type="xsd:string" use="required"/>
        <xsd:attribute name="intLanes" type="xsd:string" use="required"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="radius" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="customShape" type="boolType" use="optional"/>
        <xsd:attribute name="rightOfWay" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="edgePriority"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="fringe" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="outer"/>
                    <xsd:enumeration value="inner"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="requestType">
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="response" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="foes" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="cont" type="boolType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="stopOffsetType">
        <xsd:attribute name="value" type="nonNegativeFloatType" use="required"/>
        <xsd:attribute name="vClasses" type="xsd:string" use="optional"/>
        <xsd:attribute name="exceptions" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="connectionType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="from" type="xsd:string" use="required"/>
        <xsd:attribute name="to" type="xsd:string" use="required"/>
        <xsd:attribute name="fromLane" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="toLane" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="pass" type="boolType" use="optional"/>
        <xsd:attribute name="keepClear" type="boolType" use="optional"/>
        <xsd:attribute name="contPos" type="xsd:float" use="optional"/>
        <xsd:attribute name="visibility" type="xsd:float" use="optional"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="xsd:float" use="optional"/>
        <xsd:attribute name="length" type="xsd:float" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="uncontrolled" type="boolType" use="optional"/>
        <xsd:attribute name="via" type="xsd:string" use="optional"/>
        <xsd:attribute name="tl" type="xsd:string" use="optional"/>
        <xsd:attribute name="linkIndex" type="xsd:integer" use="optional"/>
        <xsd:attribute name="linkIndex2" type="xsd:integer" use="optional"/>
        <xsd:attribute name="dir" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="s"/>
                    <xsd:enumeration value="t"/>
                    <xsd:enumeration value="T"/>
                    <xsd:enumeration value="l"/>
                    <xsd:enumeration value="r"/>
                    <xsd:enumeration value="L"/>
                    <xsd:enumeration value="R"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="state" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="M"/>
                    <xsd:enumeration value="m"/>
                    <xsd:enumeration value="O"/>
                    <xsd:enumeration value="o"/>
                    <xsd:enumeration value="="/>
                    <xsd:enumeration value="-"/>
                    <xsd:enumeration value="s"/>
                    <xsd:enumeration value="w"/>
                    <xsd:enumeration value="Z"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="prohibitionType">
        <xsd:attribute name="prohibitor" type="xsd:string" use="required"/>
        <xsd:attribute name="prohibited" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="roundaboutType">
        <xsd:attribute name="nodes" type="xsd:string" use="required"/>
        <xsd:attribute name="edges" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="neighType">
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/examples/tools/dua-iterate/input_net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu Mar 26 16:23:52 2015 by SUMO netconvert Version dev-SVN-r18156I
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <node-files value="./tools/assign/input_dua2s.nod.xml"/>
        <edge-files value="./tools/assign/input_dua2s.edg.xml"/>
    </input>

    <output>
        <output-file value="./tools/assign/input_net.net.xml"/>
    </output>

    <processing>
        <no-internal-links value="true"/>
    </processing>

    <report>
        <verbose value="true"/>
    </report>

</configuration>
-->

<net version="0.13" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="500.00,0.00" convBoundary="0.00,0.00,2500.00,500.00" origBoundary="-500.00,0.00,2000.00,500.00" projParameter="!"/>

    <edge id="beg" from="absBeg" to="beg" priority="-1">
        <lane id="beg_0" index="0" speed="27.80" length="500.00" shape="0.00,-4.95 498.55,-4.95"/>
        <lane id="beg_1" index="1" speed="27.80" length="500.00" shape="0.00,-1.65 498.55,-1.65"/>
    </edge>
    <edge id="beg2left" from="beg" to="begleft" priority="-1">
        <lane id="beg2left_0" index="0" speed="27.80" length="503.09" shape="501.65,1.45 501.65,496.75"/>
    </edge>
    <edge id="end" from="end" to="absEnd" priority="-1">
        <lane id="end_0" index="0" speed="27.80" length="500.00" shape="1501.45,-4.95 2000.00,-4.95"/>
        <lane id="end_1" index="1" speed="27.80" length="500.00" shape="1501.45,-1.65 2000.00,-1.65"/>
    </edge>
    <edge id="left" from="begleft" to="endleft" priority="-1">
        <lane id="left_0" index="0" speed="27.80" length="1006.18" shape="503.25,498.35 1496.75,498.35"/>
    </edge>
    <edge id="left2end" from="endleft" to="end" priority="-1">
        <lane id="left2end_0" index="0" speed="27.80" length="503.09" shape="1498.35,496.75 1498.35,1.45"/>
    </edge>
    <edge id="middle" from="beg" to="end" priority="-1">
        <lane id="middle_0" index="0" speed="13.90" length="1000.00" shape="504.75,-1.65 1495.25,-1.65"/>
    </edge>
    <edge id="rend" from="absEnd" to="rabsEnd" priority="-1">
        <lane id="rend_0" index="0" speed="27.80" length="500.00" shape="2000.00,-4.95 2500.00,-4.95"/>
        <lane id="rend_1" index="1" speed="27.80" length="500.00" shape="2000.00,-1.65 2500.00,-1.65"/>
    </edge>

    <junction id="absBeg" type="unregulated" x="0.00" y="0.00" incLanes="" intLanes="" shape="-0.00,-0.05 -0.00,-6.55"/>
    <junction id="absEnd" type="priority" x="2000.00" y="0.00" incLanes="end_0 end_1" intLanes="" shape="2000.00,-0.05 2000.00,-6.55 2000.00,-0.05">
        <request index="0" response="00" foes="00"/>
        <request index="1" response="00" foes="00"/>
    </junction>
    <junction id="beg" type="priority" x="500.00" y="0.00" incLanes="beg_0 beg_1" intLanes="" shape="500.05,1.45 503.25,1.45 504.75,-0.05 504.75,-3.25 498.55,-6.55 498.55,-0.05">
        <request index="0" response="00" foes="00"/>
        <request index="1" response="00" foes="00"/>
    </junction>
    <junction id="begleft" type="priority" x="500.00" y="500.00" incLanes="beg2left_0" intLanes="" shape="503.25,499.95 503.25,496.75 500.05,496.75">
        <request index="0" response="0" foes="0"/>
    </junction>
    <junction id="end" type="priority" x="1500.00" y="0.00" incLanes="left2end_0 middle_0" intLanes="" shape="1496.75,1.45 1499.95,1.45 1501.45,-0.05 1501.45,-6.55 1495.25,-3.25 1495.25,-0.05">
        <request index="0" response="00" foes="00"/>
        <request index="1" response="00" foes="00"/>
    </junction>
    <junction id="endleft" type="priority" x="1500.00" y="500.00" incLanes="left_0" intLanes="" shape="1499.95,496.75 1496.75,496.75 1496.75,499.95">
        <request index="0" response="0" foes="0"/>
    </junction>
    <junction id="rabsEnd" type="unregulated" x="2500.00" y="0.00" incLanes="rend_0 rend_1" intLanes="" shape="2500.00,-6.55 2500.00,-0.05"/>

    <connection from="beg" to="middle" fromLane="0" toLane="0" pass="1" dir="s" state="M"/>
    <connection from="beg" to="beg2left" fromLane="1" toLane="0" pass="1" dir="l" state="M"/>
    <connection from="beg2left" to="left" fromLane="0" toLane="0" dir="r" state="M"/>
    <connection from="end" to="rend" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from="end" to="rend" fromLane="1" toLane="1" dir="s" state="M"/>
    <connection from="left" to="left2end" fromLane="0" toLane="0" dir="r" state="M"/>
    <connection from="left2end" to="end" fromLane="0" toLane="1" pass="1" dir="l" state="M"/>
    <connection from="middle" to="end" fromLane="0" toLane="0" pass="1" dir="s" state="M"/>

</net>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/examples/netconvert/hokkaido/net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu Apr 18 00:13:39 2019 by Eclipse SUMO netconvert Version v1_2_0+0017-2a947141e5
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <node-files value="input_nodes.nod.xml"/>
        <edge-files value="input_edges.edg.xml"/>
    </input>

    <output>
        <write-license value="true"/>
        <output-file value="net.net.xml"/>
        <plain-output-prefix value="plain"/>
    </output>

    <processing>
        <plain.extend-edge-shape value="true"/>
    </processing>

</configuration>
-->

<net version="1.1" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="95.49,0.00" convBoundary="0.00,0.00,1390.99,190.99" origBoundary="-95.49,0.00,1295.49,190.99" projParameter="!"/>

    <edge id=":dl_0" function="internal">
        <lane id=":dl_0_0" index="0" speed="13.89" length="0.10" shape="95.49,0.00 95.49,0.00"/>
    </edge>
    <edge id=":dr_0" function="internal">
        <lane id=":dr_0_0" index="0" speed="13.89" length="0.10" shape="1295.49,0.00 1295.49,0.00"/>
    </edge>
    <edge id=":tl_0" function="internal">
        <lane id=":tl_0_0" index="0" speed="13.89" length="0.10" shape="95.49,190.99 95.49,190.99"/>
    </edge>
    <edge id=":tr_0" function="internal">
        <lane id=":tr_0_0" index="0" speed="13.89" length="0.10" shape="1295.49,190.99 1295.49,190.99"/>
    </edge>

    <edge id="1" from="dl" to="dr" priority="-1" spreadType="center">
        <lane id="1_0" index="0" speed="13.89" length="1200.00" shape="95.49,0.00 1295.49,0.00"/>
    </edge>
    <edge id="2" from="dr" to="tr" priority="-1" spreadType="center" shape="1295.49,0.00 1312.08,1.45 1328.15,5.76 1343.24,12.79 1356.87,22.34 1368.64,34.11 1378.19,47.75 1385.23,62.83 1389.54,78.91 1390.99,95.49 1389.54,112.08 1385.23,128.15 1378.19,143.24 1368.64,156.87 1356.87,168.64 1343.24,178.19 1328.15,185.23 1312.08,189.54 1295.49,190.99">
        <lane id="2_0" index="0" speed="13.89" length="299.62" shape="1295.49,0.00 1312.08,1.45 1328.15,5.76 1343.24,12.79 1356.87,22.34 1368.64,34.11 1378.19,47.75 1385.23,62.83 1389.54,78.91 1390.99,95.49 1389.54,112.08 1385.23,128.15 1378.19,143.24 1368.64,156.87 1356.87,168.64 1343.24,178.19 1328.15,185.23 1312.08,189.54 1295.49,190.99"/>
    </edge>
    <edge id="3" from="tr" to="tl" priority="-1" spreadType="center">
        <lane id="3_0" index="0" speed="13.89" length="1200.00" shape="1295.49,190.99 95.49,190.99"/>
    </edge>
    <edge id="4" from="tl" to="dl" priority="-1" spreadType="center" shape="95.49,190.99 78.91,189.54 62.83,185.23 47.75,178.19 34.11,168.64 22.34,156.87 12.79,143.24 5.76,128.15 1.45,112.08 0.00,95.49 1.45,78.91 5.76,62.83 12.79,47.75 22.34,34.11 34.11,22.34 47.75,12.79 62.83,5.76 78.91,1.45 95.49,0.00">
        <lane id="4_0" index="0" speed="13.89" length="299.62" shape="95.49,190.99 78.91,189.54 62.83,185.23 47.75,178.19 34.11,168.64 22.34,156.87 12.79,143.24 5.76,128.15 1.45,112.08 0.00,95.49 1.45,78.91 5.76,62.83 12.79,47.75 22.34,34.11 34.11,22.34 47.75,12.79 62.83,5.76 78.91,1.45 95.49,0.00"/>
    </edge>

    <junction id="dl" type="priority" x="95.49" y="0.00" incLanes="4_0" intLanes=":dl_0_0" shape="95.56,1.60 95.56,-1.60 95.42,-1.60 95.34,-1.59">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="dr" type="priority" x="1295.49" y="0.00" incLanes="1_0" intLanes=":dr_0_0" shape="1295.42,1.60 1295.70,-1.59 1295.56,-1.60 1295.48,-1.60">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="tl" type="priority" x="95.49" y="190.99" incLanes="3_0" intLanes=":tl_0_0" shape="95.56,192.59 95.56,189.39 95.28,192.58 95.42,192.59">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="tr" type="priority" x="1295.49" y="190.99" incLanes="2_0" intLanes=":tr_0_0" shape="1295.70,192.58 1295.42,189.39 1295.42,192.59 1295.56,192.59">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>

    <connection from="1" to="2" fromLane="0" toLane="0" via=":dr_0_0" dir="s" state="M"/>
    <connection from="2" to="3" fromLane="0" toLane="0" via=":tr_0_0" dir="s" state="M"/>
    <connection from="3" to="4" fromLane="0" toLane="0" via=":tl_0_0" dir="s" state="M"/>
    <connection from="4" to="1" fromLane="0" toLane="0" via=":dl_0_0" dir="s" state="M"/>

    <connection from=":dl_0" to="1" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":dr_0" to="2" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":tl_0" to="4" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":tr_0" to="3" fromLane="0" toLane="0" dir="s" state="M"/>

</net>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/tutorial/hello/net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu Apr 18 00:13:39 2019 by Eclipse SUMO netconvert Version v1_2_0+0017-2a947141e5
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <node-files value="data/hello.nod.xml"/>
        <edge-files value="data/hello.edg.xml"/>
    </input>

    <output>
        <output-file value="data/hello.net.xml"/>
    </output>

    <report>
        <verbose value="true"/>
    </report>

</configuration>
-->

<net version="1.1" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="250.00,0.00" convBoundary="0.00,0.00,501.00,0.00" origBoundary="-250.00,0.00,251.00,0.00" projParameter="!"/>

    <edge id=":2_0" function="internal">
        <lane id=":2_0_0" index="0" speed="13.89" length="0.10" shape="500.00,-1.60 500.00,-1.60"/>
    </edge>

    <edge id="1to2" from="1" to="2" priority="-1">
        <lane id="1to2_0" index="0" speed="13.89" length="500.00" shape="0.00,-1.60 500.00,-1.60"/>
    </edge>
    <edge id="out" from="2" to="3" priority="-1">
        <lane id="out_0" index="0" speed="13.89" length="1.00" shape="500.00,-1.60 501.00,-1.60"/>
    </edge>

    <junction id="1" type="dead_end" x="0.00" y="0.00" incLanes="" intLanes="" shape="0.00,0.00 0.00,-3.20"/>
    <junction id="2" type="priority" x="500.00" y="0.00" incLanes="1to2_0" intLanes=":2_0_0" shape="500.00,0.00 500.00,-3.20 500.00,0.00">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="3" type="dead_end" x="501.00" y="0.00" incLanes="out_0" intLanes="" shape="501.00,-3.20 501.00,0.00"/>

    <connection from="1to2" to="out" fromLane="0" toLane="0" via=":2_0_0" dir="s" state="M"/>

    <connection from=":2_0" to="out" fromLane="0" toLane="0" dir="s" state="M"/>

</net>
