=== carla-simulator/carla/PythonAPI/carla/data/xsd/netstate_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:include schemaLocation="baseTypes.xsd"/>

    <xsd:element name="netstate">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="timestep"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="timestep">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="edge"/>
            </xsd:sequence>
            <xsd:attribute name="time" use="required" type="nonNegativeFloatType"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="edge">
        <xsd:complexType>
            <xsd:choice minOccurs="0" maxOccurs="unbounded" >
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="lane"/>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="vehicle"/>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="person"/>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="container"/>
            </xsd:choice>
            <xsd:attribute name="id" use="required" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="lane">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="vehicle"/>
            </xsd:sequence>
            <xsd:attribute name="id" use="required" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="vehicle">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="person"/>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="container"/>
            </xsd:sequence>
            <xsd:attribute name="id" use="required" type="xsd:string"/>
            <xsd:attribute name="pos" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="speed" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="posLat" use="optional" type="xsd:float"/>
            <xsd:attribute name="speedLat" use="optional" type="xsd:float"/>
            <xsd:attribute name="personNumber" use="optional" type="xsd:nonNegativeInteger"/>
            <xsd:attribute name="containerNumber" use="optional" type="xsd:nonNegativeInteger"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="person">
        <xsd:complexType>
            <xsd:attribute name="id" use="required" type="xsd:string"/>
            <xsd:attribute name="pos" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="angle" use="required" type="xsd:float"/>
            <xsd:attribute name="stage" use="required" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="container">
        <xsd:complexType>
            <xsd:attribute name="id" use="required" type="xsd:string"/>
            <xsd:attribute name="pos" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="angle" use="required" type="xsd:float"/>
            <xsd:attribute name="stage" use="required" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/examples/sumo/output/cross3ltl_rawdump/rawdump.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu Apr 18 00:13:39 2019 by Eclipse SUMO Version v1_2_0+0017-2a947141e5
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>
        <net-file value="net.net.xml"/>
        <route-files value="input_routes.rou.xml"/>
    </input>

    <output>
        <write-license value="true"/>
        <netstate-dump value="rawdump.xml"/>
    </output>

    <time>
        <begin value="90"/>
        <end value="120"/>
    </time>

    <processing>
        <default.speeddev value="0"/>
    </processing>

    <report>
        <duration-log.disable value="true"/>
        <no-step-log value="true"/>
    </report>

</configuration>
-->

<netstate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netstate_file.xsd">
    <timestep time="90.00"/>
    <timestep time="91.00"/>
    <timestep time="92.00"/>
    <timestep time="93.00"/>
    <timestep time="94.00"/>
    <timestep time="95.00"/>
    <timestep time="96.00"/>
    <timestep time="97.00"/>
    <timestep time="98.00"/>
    <timestep time="99.00"/>
    <timestep time="100.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.0" pos="5.10" speed="0.00"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.0" pos="5.10" speed="0.00"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="always_right.0" pos="5.10" speed="0.00"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="101.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.0" pos="7.02" speed="1.92"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.0" pos="6.42" speed="1.32"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="always_right.0" pos="7.46" speed="2.36"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="102.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.0" pos="10.66" speed="3.64"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.0" pos="9.62" speed="3.20"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="always_right.0" pos="11.19" speed="3.72"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="103.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.0" pos="16.30" speed="5.64"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.0" pos="14.84" speed="5.22"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="vertical.0" pos="5.10" speed="0.00"/>
                <vehicle id="always_right.0" pos="16.53" speed="5.34"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="104.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.0" pos="24.39" speed="8.09"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.0" pos="21.74" speed="6.90"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="vertical.0" pos="6.83" speed="1.73"/>
                <vehicle id="always_right.0" pos="23.60" speed="7.07"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="105.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.0" pos="34.67" speed="10.28"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.0" pos="30.93" speed="9.19"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="vertical.0" pos="10.62" speed="3.79"/>
                <vehicle id="always_right.0" pos="32.94" speed="9.34"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="106.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.0" pos="45.07" speed="10.39"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.0" pos="41.61" speed="10.68"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="vertical.0" pos="16.86" speed="6.24"/>
                <vehicle id="always_right.0" pos="43.77" speed="10.83"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="107.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.0" pos="55.84" speed="10.78"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.0" pos="52.61" speed="10.99"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="vertical.0" pos="24.40" speed="7.54"/>
                <vehicle id="always_right.0" pos="54.26" speed="10.49"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="108.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.0" pos="66.24" speed="10.40"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.0" pos="62.84" speed="10.24"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="vertical.0" pos="34.40" speed="10.01"/>
                <vehicle id="always_right.0" pos="64.35" speed="10.09"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="109.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.0" pos="77.27" speed="11.04"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.0" pos="73.54" speed="10.70"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="vertical.0" pos="45.50" speed="11.09"/>
                <vehicle id="always_right.0" pos="74.87" speed="10.51"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="110.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.1" pos="5.10" speed="0.00"/>
                <vehicle id="always_left.0" pos="87.52" speed="10.25"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.1" pos="5.10" speed="0.00"/>
                <vehicle id="horizontal.0" pos="84.34" speed="10.80"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="always_right.1" pos="5.10" speed="0.00"/>
                <vehicle id="vertical.0" pos="55.70" speed="10.20"/>
                <vehicle id="always_right.0" pos="84.85" speed="9.99"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="111.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.1" pos="7.19" speed="2.09"/>
                <vehicle id="always_left.0" pos="97.79" speed="10.27"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.1" pos="7.67" speed="2.57"/>
                <vehicle id="horizontal.0" pos="95.34" speed="11.00"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="always_right.1" pos="6.56" speed="1.46"/>
                <vehicle id="vertical.0" pos="65.79" speed="10.09"/>
                <vehicle id="always_right.0" pos="94.93" speed="10.08"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="112.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.1" pos="11.00" speed="3.80"/>
                <vehicle id="always_left.0" pos="107.98" speed="10.19"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
                <vehicle id="horizontal.1" pos="12.03" speed="4.36"/>
                <vehicle id="horizontal.0" pos="105.58" speed="10.24"/>
            </lane>
        </edge>
        <edge id="3fi">
            <lane id="3fi_0">
                <vehicle id="always_right.1" pos="10.25" speed="3.69"/>
                <vehicle id="vertical.0" pos="76.57" speed="10.79"/>
                <vehicle id="always_right.0" pos="105.73" speed="10.80"/>
            </lane>
        </edge>
    </timestep>
    <timestep time="113.00">
        <edge id="1fi">
            <lane id="1fi_0">
                <vehicle id="always_left.1" pos="16.19" speed="5.19"/>
                <vehicle id="always_left.0" pos="118.63" speed="10.65"/>
            </lane>
        </edge>
        <edge id="2fi">
            <lane id="2fi_0">
