=== carla-simulator/carla/PythonAPI/carla/data/xsd/types_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="baseTypes.xsd" />

    <xsd:element name="types" type="typesType">
        <xsd:key name="typeKey">
            <xsd:selector xpath="type"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
    </xsd:element>

    <xsd:complexType name="typesType">
        <xsd:sequence>
            <xsd:element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="version" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d+.\d+"></xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

</xsd:schema>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/data/typemap/osmNetconvertPedestriansNES.typ.xml
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/types_file.xsd">
    <!-- typemap for pedestrians with (N)o (E)xtra (S)idewalks -->
    <type id="highway.primary"        disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="highway.primary_link"   disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="highway.secondary"      disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="highway.secondary_link" disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="highway.tertiary"       disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="highway.tertiary_link"  disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="highway.unclassified"   disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="highway.residential"    disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
</types>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/tools/contributed/sumopy/typemap/osmNetconvertUrbanDe.typ.xml
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/types_file.xsd">
    <type id="highway.motorway"       speed="27.78"/>
    <type id="highway.motorway_link"  speed="16.67"/>
    <type id="highway.trunk"          speed="13.89"/>
    <type id="highway.trunk_link"     speed="13.89"/>
    <type id="highway.primary"        speed="13.89"/>
    <type id="highway.primary_link"   speed="13.89"/>
    <type id="highway.secondary"      speed="13.89"/>
    <type id="highway.secondary_link" speed="13.89"/>
    <type id="highway.tertiary"       speed="13.89"/>
    <type id="highway.tertiary_link"  speed="13.89"/>
</types>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/examples/netconvert/OSM/adlershof_dlr/plain.typ.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu Apr 18 00:13:39 2019 by Eclipse SUMO netconvert Version v1_2_0+0017-2a947141e5
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <osm-files value="osm.xml"/>
    </input>

    <output>
        <write-license value="true"/>
        <output-file value="net.net.xml"/>
        <plain-output-prefix value="plain"/>
        <output.street-names value="true"/>
    </output>

    <projection>
        <proj.utm value="true"/>
        <proj.plain-geo value="true"/>
    </projection>

    <tls_building>
        <tls.red.time value="10"/>
    </tls_building>

    <junctions>
        <no-internal-links value="true"/>
    </junctions>

    <report>
        <verbose value="true"/>
    </report>

</configuration>
-->

<types version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/types_file.xsd">
    <type id="highway.bridleway" priority="1" numLanes="1" speed="2.78" allow="pedestrian" oneway="1" width="2.00"/>
    <type id="highway.bus_guideway" priority="1" numLanes="1" speed="27.78" allow="bus" oneway="1"/>
    <type id="highway.cycleway" priority="1" numLanes="1" speed="8.33" allow="bicycle" oneway="0" width="1.00"/>
    <type id="highway.footway" priority="1" numLanes="1" speed="2.78" allow="pedestrian" oneway="1" width="2.00"/>
    <type id="highway.ford" priority="1" numLanes="1" speed="2.78" allow="army" oneway="0"/>
    <type id="highway.living_street" priority="2" numLanes="1" speed="2.78" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="highway.motorway" priority="14" numLanes="2" speed="39.44" allow="private emergency authority army vip passenger hov taxi bus coach delivery truck trailer motorcycle evehicle custom1 custom2" oneway="1"/>
    <type id="highway.motorway_link" priority="9" numLanes="1" speed="22.22" allow="private emergency authority army vip passenger hov taxi bus coach delivery truck trailer motorcycle evehicle custom1 custom2" oneway="1"/>
    <type id="highway.path" priority="1" numLanes="1" speed="2.78" allow="bicycle pedestrian" oneway="1" width="2.00"/>
    <type id="highway.pedestrian" priority="1" numLanes="1" speed="2.78" allow="pedestrian" oneway="1" width="2.00"/>
    <type id="highway.primary" priority="12" numLanes="2" speed="27.78" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="highway.primary_link" priority="7" numLanes="1" speed="22.22" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="highway.raceway" priority="15" numLanes="2" speed="83.33" allow="vip" oneway="0"/>
    <type id="highway.residential" priority="3" numLanes="1" speed="13.89" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="highway.secondary" priority="11" numLanes="2" speed="27.78" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="highway.secondary_link" priority="6" numLanes="1" speed="22.22" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="highway.service" priority="1" numLanes="1" speed="5.56" allow="delivery bicycle pedestrian" oneway="0"/>
    <type id="highway.stairs" priority="1" numLanes="1" speed="1.39" allow="pedestrian" oneway="1" width="2.00"/>
    <type id="highway.step" priority="1" numLanes="1" speed="1.39" allow="pedestrian" oneway="1" width="2.00"/>
    <type id="highway.steps" priority="1" numLanes="1" speed="1.39" allow="pedestrian" oneway="1" width="2.00"/>
    <type id="highway.tertiary" priority="10" numLanes="1" speed="22.22" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="highway.tertiary_link" priority="5" numLanes="1" speed="22.22" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="highway.track" priority="1" numLanes="1" speed="5.56" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="highway.trunk" priority="13" numLanes="2" speed="27.78" disallow="tram rail_urban rail rail_electric bicycle pedestrian ship" oneway="0"/>
    <type id="highway.trunk_link" priority="8" numLanes="1" speed="22.22" disallow="tram rail_urban rail rail_electric bicycle pedestrian ship" oneway="0"/>
    <type id="highway.unclassified" priority="4" numLanes="1" speed="13.89" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="highway.unsurfaced" priority="1" numLanes="1" speed="8.33" disallow="tram rail_urban rail rail_electric ship" oneway="0"/>
    <type id="railway.light_rail" priority="19" numLanes="1" speed="27.78" allow="rail_urban" oneway="1"/>
    <type id="railway.preserved" priority="16" numLanes="1" speed="27.78" allow="rail" oneway="1"/>
    <type id="railway.rail" priority="20" numLanes="1" speed="83.33" allow="rail rail_electric" oneway="1"/>
    <type id="railway.subway" priority="18" numLanes="1" speed="27.78" allow="rail_urban" oneway="1"/>
    <type id="railway.tram" priority="17" numLanes="1" speed="13.89" allow="tram" oneway="1"/>

</types>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/data/typemap/opendriveNetconvert.typ.xml
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/types_file.xsd">
    <type id="driving"       priority="1"  speed="13.89" width="3.65" disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="stop"          priority="1"  speed="13.89" width="3.65" disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="restricted"    priority="0"  speed="13.89" width="3.65" disallow="all"/> <!-- ambiguous semantics. Could mean bus-lane as well as fully-area restricted (but surfaced) lane area (as seen in official examples) -->
    <type id="parking"       priority="1"  speed="1.39"  width="2.50" disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="entry"         priority="1"  speed="22.22" width="3.65" disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="exit"          priority="1"  speed="22.22" width="3.65" disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="offRamp"       priority="1"  speed="22.22" width="3.65" disallow="pedestrian bicycle moped rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="onRamp"        priority="1"  speed="22.22" width="3.65" disallow="pedestrian bicycle moped rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="roadWorks"     priority="0"  speed="1.39"  width="3.65" allow="authority"/>
    <type id="tram"          priority="2"  speed="13.89" width="3.65" allow="tram"/>
    <type id="rail"          priority="3"  speed="33.33" width="3.65" allow="rail rail_urban rail_electric rail_fast"/>

    <!-- should be enabled via additional typemaps -->
    <!--
    <type id="biking"        priority="-1" speed="5.56"  width="1.50" allow="bicycle"      />
    <type id="sidewalk"      priority="-2" speed="2.78"  width="2.50" allow="pedestrian"   />
    -->

    <!-- discarded -->
    <type id="none"          priority="0"  speed="1.39" width="1.0"   disallow="all"          discard="true"/>
    <type id="shoulder"      priority="0"  speed="1.39" width="1.0"   disallow="all"          discard="true"/>
    <type id="border"        priority="0"  speed="1.39" width="0.1"   disallow="all"          discard="true"/>
    <type id="median"        priority="0"  speed="1.39" width="0.1"   disallow="all"          discard="true"/>
    <type id="special1"      priority="1"  speed="22.22" width="3.65" allow="custom1"         discard="true"/>
    <type id="special2"      priority="1"  speed="22.22" width="3.65" allow="custom2"         discard="true"/>
    <type id="special3"      priority="1"  speed="22.22" width="3.65" allow="custom1 custom2" discard="true"/>

    <!-- deprecated -->
    <type id="mwyEntry"      priority="1"  speed="22.22" width="3.65" disallow="pedestrian bicycle moped rail rail_urban rail_electric rail_fast tram ship"/>
    <type id="mwyExit"       priority="1"  speed="22.22" width="3.65" disallow="pedestrian bicycle moped rail rail_urban rail_electric rail_fast tram ship"/>

    <!-- not fully implemented -->
    <type id="bidirectional" priority="1"  speed="1.39"  width="3.65" disallow="pedestrian rail rail_urban rail_electric rail_fast tram ship"/> 
</types>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/tools/contributed/sumopy/typemap/osmNetconvert.typ.xml
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/types_file.xsd">
    <type id="highway.motorway"       numLanes="2" speed="44.44" priority="13" oneway="true"  disallow="pedestrian bicycle moped rail rail_urban rail_electric tram ship"/>
    <type id="highway.motorway_link"  numLanes="1" speed="22.22" priority="12" oneway="true"  disallow="pedestrian bicycle moped rail rail_urban rail_electric tram ship"/>
    <type id="highway.trunk"          numLanes="2" speed="27.78" priority="11" oneway="false" disallow="pedestrian bicycle rail rail_urban rail_electric tram ship"/>
    <type id="highway.trunk_link"     numLanes="1" speed="22.22" priority="10" oneway="false" disallow="pedestrian bicycle rail rail_urban rail_electric tram ship"/>
    <type id="highway.primary"        numLanes="2" speed="27.78" priority="9"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.primary_link"   numLanes="1" speed="22.22" priority="8"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.secondary"      numLanes="2" speed="27.78" priority="7"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.secondary_link" numLanes="1" speed="22.22" priority="6"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.tertiary"       numLanes="1" speed="22.22" priority="6"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.tertiary_link"  numLanes="1" speed="22.22" priority="5"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.unclassified"   numLanes="1" speed="13.89" priority="5"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.residential"    numLanes="1" speed="13.89" priority="4"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.living_street"  numLanes="1" speed="2.78"  priority="3"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.service"        numLanes="1" speed="5.56"  priority="2"  oneway="false" allow="delivery pedestrian bicycle"/>
    <type id="highway.track"          numLanes="1" speed="5.56"  priority="1"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.services"       numLanes="1" speed="8.33"  priority="1"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>
    <type id="highway.unsurfaced"     numLanes="1" speed="8.33"  priority="1"  oneway="false" disallow="rail rail_urban rail_electric tram ship"/>

    <!-- everything which serves mainly pedestrians is oneway because all current pedestrian models do not care about direction -->
    <type id="highway.footway"        numLanes="1" speed="8.33"  priority="1"  oneway="true"  width="2" allow="pedestrian"/>
    <type id="highway.pedestrian"     numLanes="1" speed="8.33"  priority="1"  oneway="true"  width="2" allow="pedestrian"/>
    <type id="highway.path"           numLanes="1" speed="2.78"  priority="1"  oneway="true"  width="2" allow="pedestrian bicycle"/>
    <type id="highway.bridleway"      numLanes="1" speed="2.78"  priority="1"  oneway="true"  width="2" allow="pedestrian"/>
    <type id="highway.cycleway"       numLanes="1" speed="5.56"  priority="1"  oneway="false" width="1" allow="bicycle"/>
    <type id="highway.step"           numLanes="1" speed="1.39"  priority="1"  oneway="true"  width="2" allow="pedestrian"/>
    <type id="highway.steps"          numLanes="1" speed="1.39"  priority="1"  oneway="true"  width="2" allow="pedestrian"/>
    <type id="highway.stairs"         numLanes="1" speed="1.39"  priority="1"  oneway="true"  width="2" allow="pedestrian"/>

    <type id="highway.bus_guideway"   numLanes="1" speed="8.33"  priority="1"  oneway="true"  allow="bus"/>
    <type id="highway.raceway"        numLanes="2" speed="83.33" priority="14" oneway="false" allow="vip"/>
    <type id="highway.ford"           numLanes="1" speed="2.78"  priority="1"  oneway="false" allow="army"/>

    <type id="railway.rail"           numLanes="1" speed="83.33" priority="15" oneway="true"  allow="rail rail_electric"/>
    <type id="railway.tram"           numLanes="1" speed="13.89" priority="15" oneway="true"  allow="tram"/>
    <type id="railway.light_rail"     numLanes="1" speed="27.78" priority="15" oneway="true"  allow="rail_urban"/>
    <type id="railway.subway"         numLanes="1" speed="27.78" priority="15" oneway="true"  allow="rail_urban"/>
    <type id="railway.preserved"      numLanes="1" speed="27.78" priority="15" oneway="true"  allow="rail"/>

</types>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/tools/contributed/sumopy/typemap/osmNetconvertPedestrians.typ.xml
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/types_file.xsd">
    <type id="highway.primary"        sidewalkWidth="3" disallow="pedestrian rail rail_urban rail_electric tram ship"/>
    <type id="highway.primary_link"   sidewalkWidth="3" disallow="pedestrian rail rail_urban rail_electric tram ship"/>
    <type id="highway.secondary"      sidewalkWidth="3" disallow="pedestrian rail rail_urban rail_electric tram ship"/>
    <type id="highway.secondary_link" sidewalkWidth="3" disallow="pedestrian rail rail_urban rail_electric tram ship"/>
    <type id="highway.tertiary"       sidewalkWidth="3" disallow="pedestrian rail rail_urban rail_electric tram ship"/>
    <type id="highway.tertiary_link"  sidewalkWidth="2" disallow="pedestrian rail rail_urban rail_electric tram ship"/>
    <type id="highway.unclassified"   sidewalkWidth="2" disallow="pedestrian rail rail_urban rail_electric tram ship"/>
    <type id="highway.residential"    sidewalkWidth="2" disallow="pedestrian rail rail_urban rail_electric tram ship"/>
</types>
