=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/data/xsd/emission_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:include schemaLocation="baseTypes.xsd"/>

    <xsd:element name="emission-export">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="timestep"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="timestep">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="vehicle"/>
            </xsd:sequence>
            <xsd:attribute name="time" use="required" type="nonNegativeFloatType"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="vehicle">
        <xsd:complexType>
            <xsd:attribute name="id" use="required" type="xsd:string"/>
            <xsd:attribute name="eclass" use="required" type="xsd:string"/>
            <xsd:attribute name="CO" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="CO2" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="HC" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="PMx" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="NOx" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="fuel" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="electricity" use="required" type="xsd:float"/>
            <xsd:attribute name="noise" use="required" type="nonNegativeFloatType"/>

            <xsd:attribute name="route" use="required" type="xsd:string"/>
            <xsd:attribute name="type" use="required" type="xsd:string"/>

            <xsd:attribute name="waiting" use="optional" type="nonNegativeFloatType"/>
            <xsd:attribute name="lane" use="optional" type="xsd:string"/>
            <xsd:attribute name="edge" use="optional" type="xsd:string"/>
            <xsd:attribute name="pos" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="speed" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="angle" type="xsd:float" use="required"/>
            <xsd:attribute name="x" type="xsd:float" use="required"/>
            <xsd:attribute name="y" type="xsd:float" use="required"/>
            <xsd:attribute name="z" type="xsd:float" use="optional"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/examples/sumo/output/cross3ltl_emission/emissions.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu Apr 18 00:13:39 2019 by Eclipse SUMO Version v1_2_0+0017-2a947141e5
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>
        <net-file value="net.net.xml"/>
        <route-files value="input_routes.rou.xml"/>
    </input>

    <output>
        <write-license value="true"/>
        <emission-output value="emissions.xml"/>
    </output>

    <time>
        <begin value="0"/>
        <end value="120"/>
    </time>

    <processing>
        <default.speeddev value="0"/>
    </processing>

    <report>
        <duration-log.disable value="true"/>
        <no-step-log value="true"/>
    </report>

</configuration>
-->

<emission-export xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/emission_file.xsd">
    <timestep time="0.00"/>
    <timestep time="1.00"/>
    <timestep time="2.00"/>
    <timestep time="3.00"/>
    <timestep time="4.00"/>
    <timestep time="5.00"/>
    <timestep time="6.00"/>
    <timestep time="7.00"/>
    <timestep time="8.00"/>
    <timestep time="9.00"/>
    <timestep time="10.00"/>
    <timestep time="11.00"/>
    <timestep time="12.00"/>
    <timestep time="13.00"/>
    <timestep time="14.00"/>
    <timestep time="15.00"/>
    <timestep time="16.00"/>
    <timestep time="17.00"/>
    <timestep time="18.00"/>
    <timestep time="19.00"/>
    <timestep time="20.00"/>
    <timestep time="21.00"/>
    <timestep time="22.00"/>
    <timestep time="23.00"/>
    <timestep time="24.00"/>
    <timestep time="25.00"/>
    <timestep time="26.00"/>
    <timestep time="27.00"/>
    <timestep time="28.00"/>
    <timestep time="29.00"/>
    <timestep time="30.00"/>
    <timestep time="31.00"/>
    <timestep time="32.00"/>
    <timestep time="33.00"/>
    <timestep time="34.00"/>
    <timestep time="35.00"/>
    <timestep time="36.00"/>
    <timestep time="37.00"/>
    <timestep time="38.00"/>
    <timestep time="39.00"/>
    <timestep time="40.00"/>
    <timestep time="41.00"/>
    <timestep time="42.00"/>
    <timestep time="43.00"/>
    <timestep time="44.00"/>
    <timestep time="45.00"/>
    <timestep time="46.00"/>
    <timestep time="47.00"/>
    <timestep time="48.00"/>
    <timestep time="49.00"/>
    <timestep time="50.00"/>
    <timestep time="51.00"/>
    <timestep time="52.00"/>
    <timestep time="53.00"/>
    <timestep time="54.00"/>
    <timestep time="55.00"/>
    <timestep time="56.00"/>
    <timestep time="57.00"/>
    <timestep time="58.00"/>
    <timestep time="59.00"/>
    <timestep time="60.00"/>
    <timestep time="61.00"/>
    <timestep time="62.00"/>
    <timestep time="63.00"/>
    <timestep time="64.00"/>
    <timestep time="65.00"/>
    <timestep time="66.00"/>
    <timestep time="67.00"/>
    <timestep time="68.00"/>
    <timestep time="69.00"/>
    <timestep time="70.00"/>
    <timestep time="71.00"/>
    <timestep time="72.00"/>
    <timestep time="73.00"/>
    <timestep time="74.00"/>
    <timestep time="75.00"/>
    <timestep time="76.00"/>
    <timestep time="77.00"/>
    <timestep time="78.00"/>
    <timestep time="79.00"/>
    <timestep time="80.00"/>
    <timestep time="81.00"/>
    <timestep time="82.00"/>
    <timestep time="83.00"/>
    <timestep time="84.00"/>
    <timestep time="85.00"/>
    <timestep time="86.00"/>
    <timestep time="87.00"/>
    <timestep time="88.00"/>
    <timestep time="89.00"/>
    <timestep time="90.00"/>
    <timestep time="91.00"/>
    <timestep time="92.00"/>
    <timestep time="93.00"/>
    <timestep time="94.00"/>
    <timestep time="95.00"/>
    <timestep time="96.00"/>
    <timestep time="97.00"/>
    <timestep time="98.00"/>
    <timestep time="99.00"/>
    <timestep time="100.00">
        <vehicle id="always_left.0" eclass="HBEFA3/PC_G_EU4" CO2="2624.72" CO="164.78" HC="0.81" NOx="1.20" PMx="0.07" fuel="1.13" electricity="0.00" noise="55.94" route="always_left" type="DEFAULT_VEHTYPE" waiting="0.00" lane="1fi_0" pos="5.10" speed="0.00" angle="90.00" x="5.10" y="498.35"/>
        <vehicle id="always_right.0" eclass="HBEFA3/PC_G_EU4" CO2="2624.72" CO="164.78" HC="0.81" NOx="1.20" PMx="0.07" fuel="1.13" electricity="0.00" noise="55.94" route="always_right" type="DEFAULT_VEHTYPE" waiting="0.00" lane="3fi_0" pos="5.10" speed="0.00" angle="0.00" x="501.65" y="5.10"/>
        <vehicle id="horizontal.0" eclass="HBEFA3/PC_G_EU4" CO2="2624.72" CO="164.78" HC="0.81" NOx="1.20" PMx="0.07" fuel="1.13" electricity="0.00" noise="55.94" route="horizontal" type="DEFAULT_VEHTYPE" waiting="0.00" lane="2fi_0" pos="5.10" speed="0.00" angle="270.00" x="994.90" y="501.65"/>
    </timestep>
    <timestep time="101.00">
        <vehicle id="always_left.0" eclass="HBEFA3/PC_G_EU4" CO2="3364.52" CO="147.63" HC="0.75" NOx="1.50" PMx="0.08" fuel="1.45" electricity="0.00" noise="65.12" route="always_left" type="DEFAULT_VEHTYPE" waiting="0.00" lane="1fi_0" pos="7.02" speed="1.92" angle="90.00" x="7.02" y="498.35"/>
        <vehicle id="always_right.0" eclass="HBEFA3/PC_G_EU4" CO2="3815.82" CO="149.89" HC="0.77" NOx="1.70" PMx="0.08" fuel="1.64" electricity="0.00" noise="67.24" route="always_right" type="DEFAULT_VEHTYPE" waiting="0.00" lane="3fi_0" pos="7.46" speed="2.36" angle="0.00" x="501.65" y="7.46"/>
        <vehicle id="horizontal.0" eclass="HBEFA3/PC_G_EU4" CO2="2919.85" CO="148.29" HC="0.74" NOx="1.31" PMx="0.07" fuel="1.26" electricity="0.00" noise="62.24" route="horizontal" type="DEFAULT_VEHTYPE" waiting="0.00" lane="2fi_0" pos="6.42" speed="1.32" angle="270.00" x="993.58" y="501.65"/>
    </timestep>
    <timestep time="102.00">
        <vehicle id="always_left.0" eclass="HBEFA3/PC_G_EU4" CO2="3890.91" CO="132.03" HC="0.69" NOx="1.70" PMx="0.08" fuel="1.67" electricity="0.00" noise="64.97" route="always_left" type="DEFAULT_VEHTYPE" waiting="0.00" lane="1fi_0" pos="10.66" speed="3.64" angle="90.00" x="10.66" y="498.35"/>
        <vehicle id="always_right.0" eclass="HBEFA3/PC_G_EU4" CO2="3574.17" CO="124.28" HC="0.65" NOx="1.55" PMx="0.07" fuel="1.54" electricity="0.00" noise="63.44" route="always_right" type="DEFAULT_VEHTYPE" waiting="0.00" lane="3fi_0" pos="11.19" speed="3.72" angle="0.00" x="501.65" y="11.19"/>
        <vehicle id="horizontal.0" eclass="HBEFA3/PC_G_EU4" CO2="3858.95" CO="137.92" HC="0.72" NOx="1.70" PMx="0.08" fuel="1.66" electricity="0.00" noise="65.48" route="horizontal" type="DEFAULT_VEHTYPE" waiting="0.00" lane="2fi_0" pos="9.62" speed="3.20" angle="270.00" x="990.38" y="501.65"/>
    </timestep>
    <timestep time="103.00">
        <vehicle id="always_left.0" eclass="HBEFA3/PC_G_EU4" CO2="5088.13" CO="129.05" HC="0.71" NOx="2.21" PMx="0.10" fuel="2.19" electricity="0.00" noise="67.06" route="always_left" type="DEFAULT_VEHTYPE" waiting="0.00" lane="1fi_0" pos="16.30" speed="5.64" angle="90.00" x="16.30" y="498.35"/>
        <vehicle id="always_right.0" eclass="HBEFA3/PC_G_EU4" CO2="4410.91" CO="119.02" HC="0.65" NOx="1.90" PMx="0.09" fuel="1.90" electricity="0.00" noise="65.27" route="always_right" type="DEFAULT_VEHTYPE" waiting="0.00" lane="3fi_0" pos="16.53" speed="5.34" angle="0.00" x="501.65" y="16.53"/>
        <vehicle id="horizontal.0" eclass="HBEFA3/PC_G_EU4" CO2="4916.18" CO="131.04" HC="0.71" NOx="2.14" PMx="0.10" fuel="2.11" electricity="0.00" noise="66.96" route="horizontal" type="DEFAULT_VEHTYPE" waiting="0.00" lane="2fi_0" pos="14.84" speed="5.22" angle="270.00" x="985.16" y="501.65"/>
        <vehicle id="vertical.0" eclass="HBEFA3/PC_G_EU4" CO2="2624.72" CO="164.78" HC="0.81" NOx="1.20" PMx="0.07" fuel="1.13" electricity="0.00" noise="55.94" route="vertical" type="DEFAULT_VEHTYPE" waiting="0.00" lane="3fi_0" pos="5.10" speed="0.00" angle="0.00" x="501.65" y="5.10"/>
    </timestep>
    <timestep time="104.00">
        <vehicle id="always_left.0" eclass="HBEFA3/PC_G_EU4" CO2="7234.49" CO="144.09" HC="0.83" NOx="3.16" PMx="0.15" fuel="3.11" electricity="0.00" noise="70.06" route="always_left" type="DEFAULT_VEHTYPE" waiting="0.00" lane="1fi_0" pos="24.39" speed="8.09" angle="90.00" x="24.39" y="498.35"/>
        <vehicle id="always_right.0" eclass="HBEFA3/PC_G_EU4" CO2="5282.70" CO="115.41" HC="0.65" NOx="2.27" PMx="0.10" fuel="2.27" electricity="0.00" noise="66.54" route="always_right" type="DEFAULT_VEHTYPE" waiting="0.00" lane="3fi_0" pos="23.60" speed="7.07" angle="0.00" x="501.65" y="23.60"/>
        <vehicle id="horizontal.0" eclass="HBEFA3/PC_G_EU4" CO2="5123.08" CO="114.13" HC="0.64" NOx="2.20" PMx="0.10" fuel="2.20" electricity="0.00" noise="66.26" route="horizontal" type="DEFAULT_VEHTYPE" waiting="0.00" lane="2fi_0" pos="21.74" speed="6.90" angle="270.00" x="978.26" y="501.65"/>
        <vehicle id="vertical.0" eclass="HBEFA3/PC_G_EU4" CO2="3207.71" CO="147.37" HC="0.75" NOx="1.43" PMx="0.07" fuel="1.38" electricity="0.00" noise="64.24" route="vertical" type="DEFAULT_VEHTYPE" waiting="0.00" lane="3fi_0" pos="6.83" speed="1.73" angle="0.00" x="501.65" y="6.83"/>
    </timestep>
    <timestep time="105.00">
        <vehicle id="always_left.0" eclass="HBEFA3/PC_G_EU4" CO2="8017.70" CO="138.21" HC="0.82" NOx="3.47" PMx="0.17" fuel="3.45" electricity="0.00" noise="70.08" route="always_left" type="DEFAULT_VEHTYPE" waiting="0.00" lane="1fi_0" pos="34.67" speed="10.28" angle="90.00" x="34.67" y="498.35"/>
        <vehicle id="always_right.0" eclass="HBEFA3/PC_G_EU4" CO2="7624.06" CO="139.06" HC="0.82" NOx="3.31" PMx="0.16" fuel="3.28" electricity="0.00" noise="69.92" route="always_right" type="DEFAULT_VEHTYPE" waiting="0.00" lane="3fi_0" pos="32.94" speed="9.34" angle="0.00" x="501.65" y="32.94"/>
