=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/data/xsd/vtypeprobe_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:include schemaLocation="baseTypes.xsd"/>

    <xsd:element name="vehicle-type-probes">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="timestep"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="timestep">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="vehicle"/>
            </xsd:sequence>
            <xsd:attribute name="time" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="id" use="required" type="xsd:string"/>
            <xsd:attribute name="vType" use="required" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="vehicle">
        <xsd:complexType>
            <xsd:attribute name="id" use="required" type="xsd:string"/>
            <xsd:attribute name="x" type="xsd:float" use="required"/>
            <xsd:attribute name="y" type="xsd:float" use="required"/>
            <xsd:attribute name="z" type="xsd:float" use="optional"/>
            <xsd:attribute name="lon" type="xsd:float" use="optional"/>
            <xsd:attribute name="lat" type="xsd:float" use="optional"/>
            <xsd:attribute name="speed" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="pos" use="required" type="nonNegativeFloatType"/>
            <xsd:attribute name="lane" use="optional" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== carla-simulator/carla/Co-Simulation/Sumo/sumo-1.7.0/docs/examples/sumo/output/cross3ltl_vtypeprobe/vtypeprobe.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu Apr 18 00:13:39 2019 by Eclipse SUMO Version v1_2_0+0017-2a947141e5
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>
        <net-file value="net.net.xml"/>
        <route-files value="input_routes.rou.xml"/>
        <additional-files value="input_additional.add.xml"/>
    </input>

    <output>
        <write-license value="true"/>
    </output>

    <time>
        <begin value="0"/>
        <end value="220"/>
    </time>

    <processing>
        <default.speeddev value="0"/>
    </processing>

    <report>
        <duration-log.disable value="true"/>
        <no-step-log value="true"/>
    </report>

</configuration>
-->

<vehicle-type-probes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/vtypeprobe_file.xsd">
    <timestep time="0.00" id="test1" vType="DEFAULT_VEHTYPE"/>
    <timestep time="10.00" id="test1" vType="DEFAULT_VEHTYPE"/>
    <timestep time="20.00" id="test1" vType="DEFAULT_VEHTYPE"/>
    <timestep time="30.00" id="test1" vType="DEFAULT_VEHTYPE"/>
    <timestep time="40.00" id="test1" vType="DEFAULT_VEHTYPE"/>
    <timestep time="50.00" id="test1" vType="DEFAULT_VEHTYPE"/>
    <timestep time="60.00" id="test1" vType="DEFAULT_VEHTYPE"/>
    <timestep time="70.00" id="test1" vType="DEFAULT_VEHTYPE"/>
    <timestep time="80.00" id="test1" vType="DEFAULT_VEHTYPE"/>
    <timestep time="90.00" id="test1" vType="DEFAULT_VEHTYPE"/>
    <timestep time="100.00" id="test1" vType="DEFAULT_VEHTYPE">
        <vehicle id="always_left.0" lane="1fi_0" pos="5.10" x="5.10" y="498.35" speed="0.00"/>
        <vehicle id="always_right.0" lane="3fi_0" pos="5.10" x="501.65" y="5.10" speed="0.00"/>
        <vehicle id="horizontal.0" lane="2fi_0" pos="5.10" x="994.90" y="501.65" speed="0.00"/>
    </timestep>
    <timestep time="110.00" id="test1" vType="DEFAULT_VEHTYPE">
        <vehicle id="always_left.0" lane="1fi_0" pos="87.52" x="87.52" y="498.35" speed="10.25"/>
        <vehicle id="always_left.1" lane="1fi_0" pos="5.10" x="5.10" y="498.35" speed="0.00"/>
        <vehicle id="always_right.0" lane="3fi_0" pos="84.85" x="501.65" y="84.85" speed="9.99"/>
        <vehicle id="always_right.1" lane="3fi_0" pos="5.10" x="501.65" y="5.10" speed="0.00"/>
        <vehicle id="horizontal.0" lane="2fi_0" pos="84.34" x="915.66" y="501.65" speed="10.80"/>
        <vehicle id="horizontal.1" lane="2fi_0" pos="5.10" x="994.90" y="501.65" speed="0.00"/>
        <vehicle id="vertical.0" lane="3fi_0" pos="55.70" x="501.65" y="55.70" speed="10.20"/>
    </timestep>
    <timestep time="120.00" id="test1" vType="DEFAULT_VEHTYPE">
        <vehicle id="always_left.0" lane="1fi_0" pos="190.22" x="190.22" y="498.35" speed="10.90"/>
        <vehicle id="always_left.1" lane="1fi_0" pos="84.54" x="84.54" y="498.35" speed="10.83"/>
        <vehicle id="always_left.2" lane="1fi_0" pos="5.10" x="5.10" y="498.35" speed="0.00"/>
        <vehicle id="always_right.0" lane="3fi_0" pos="191.10" x="501.65" y="191.10" speed="10.66"/>
        <vehicle id="always_right.1" lane="3fi_0" pos="87.08" x="501.65" y="87.08" speed="10.34"/>
        <vehicle id="always_right.2" lane="3fi_0" pos="5.10" x="501.65" y="5.10" speed="0.00"/>
        <vehicle id="horizontal.0" lane="2fi_0" pos="189.46" x="810.54" y="501.65" speed="10.54"/>
        <vehicle id="horizontal.1" lane="2fi_0" pos="86.65" x="913.35" y="501.65" speed="10.77"/>
        <vehicle id="horizontal.2" lane="2fi_0" pos="5.10" x="994.90" y="501.65" speed="0.00"/>
        <vehicle id="vertical.0" lane="3fi_0" pos="160.83" x="501.65" y="160.83" speed="10.21"/>
        <vehicle id="vertical.1" lane="3fi_0" pos="55.15" x="501.65" y="55.15" speed="9.91"/>
    </timestep>
    <timestep time="130.00" id="test1" vType="DEFAULT_VEHTYPE">
        <vehicle id="always_left.0" lane="1si_2" pos="49.98" x="301.48" y="498.35" speed="12.72"/>
        <vehicle id="always_left.1" lane="1fi_0" pos="187.44" x="187.44" y="498.35" speed="9.88"/>
        <vehicle id="always_left.2" lane="1fi_0" pos="89.75" x="89.75" y="498.35" speed="10.81"/>
        <vehicle id="always_left.3" lane="1fi_0" pos="5.10" x="5.10" y="498.35" speed="0.00"/>
        <vehicle id="always_right.0" lane="3si_0" pos="55.91" x="508.25" y="307.41" speed="13.87"/>
        <vehicle id="always_right.1" lane="3fi_0" pos="191.85" x="501.65" y="191.85" speed="10.12"/>
        <vehicle id="always_right.2" lane="3fi_0" pos="90.38" x="501.65" y="90.38" speed="11.01"/>
        <vehicle id="always_right.3" lane="3fi_0" pos="5.10" x="501.65" y="5.10" speed="0.00"/>
        <vehicle id="horizontal.0" lane="2si_1" pos="51.61" x="696.89" y="504.95" speed="13.84"/>
        <vehicle id="horizontal.1" lane="2fi_0" pos="189.86" x="810.14" y="501.65" speed="10.07"/>
        <vehicle id="horizontal.2" lane="2fi_0" pos="85.12" x="914.88" y="501.65" speed="10.95"/>
        <vehicle id="horizontal.3" lane="2fi_0" pos="5.10" x="994.90" y="501.65" speed="0.00"/>
        <vehicle id="vertical.0" lane="3si_1" pos="14.64" x="504.95" y="266.14" speed="12.66"/>
        <vehicle id="vertical.1" lane="3fi_0" pos="158.60" x="501.65" y="158.60" speed="10.62"/>
        <vehicle id="vertical.2" lane="3fi_0" pos="56.64" x="501.65" y="56.64" speed="10.28"/>
    </timestep>
    <timestep time="140.00" id="test1" vType="DEFAULT_VEHTYPE">
        <vehicle id="always_left.0" lane="1si_2" pos="183.31" x="434.81" y="498.35" speed="13.45"/>
        <vehicle id="always_left.1" lane="1si_2" pos="47.78" x="299.28" y="498.35" speed="12.76"/>
        <vehicle id="always_left.2" lane="1fi_0" pos="194.27" x="194.27" y="498.35" speed="9.99"/>
        <vehicle id="always_left.3" lane="1fi_0" pos="85.00" x="85.00" y="498.35" speed="10.36"/>
        <vehicle id="always_left.4" lane="1fi_0" pos="5.10" x="5.10" y="498.35" speed="0.00"/>
        <vehicle id="always_right.0" lane="3si_0" pos="188.38" x="508.25" y="439.88" speed="13.67"/>
        <vehicle id="always_right.1" lane="3si_0" pos="53.37" x="508.25" y="304.87" speed="13.53"/>
        <vehicle id="always_right.2" lane="3fi_0" pos="195.79" x="501.65" y="195.79" speed="10.33"/>
        <vehicle id="always_right.3" lane="3fi_0" pos="84.65" x="501.65" y="84.65" speed="10.06"/>
        <vehicle id="always_right.4" lane="3fi_0" pos="5.10" x="501.65" y="5.10" speed="0.00"/>
        <vehicle id="horizontal.0" lane="2si_1" pos="183.58" x="564.92" y="504.95" speed="13.76"/>
        <vehicle id="horizontal.1" lane="2si_1" pos="51.65" x="696.85" y="504.95" speed="13.65"/>
        <vehicle id="horizontal.2" lane="2fi_0" pos="188.05" x="811.95" y="501.65" speed="10.26"/>
        <vehicle id="horizontal.3" lane="2fi_0" pos="83.00" x="917.00" y="501.65" speed="9.90"/>
        <vehicle id="horizontal.4" lane="2fi_0" pos="5.10" x="994.90" y="501.65" speed="0.00"/>
        <vehicle id="vertical.0" lane="3si_1" pos="147.97" x="504.95" y="399.47" speed="13.23"/>
        <vehicle id="vertical.1" lane="3si_1" pos="10.72" x="504.95" y="262.22" speed="12.15"/>
        <vehicle id="vertical.2" lane="3fi_0" pos="159.23" x="501.65" y="159.23" speed="9.87"/>
        <vehicle id="vertical.3" lane="3fi_0" pos="49.85" x="501.65" y="49.85" speed="10.19"/>
    </timestep>
    <timestep time="150.00" id="test1" vType="DEFAULT_VEHTYPE">
        <vehicle id="always_left.0" lane="4o_0" pos="18.10" x="501.65" y="529.45" speed="10.64"/>
        <vehicle id="always_left.1" lane="1si_2" pos="179.30" x="430.80" y="498.35" speed="13.03"/>
        <vehicle id="always_left.2" lane="1si_2" pos="55.91" x="307.41" y="498.35" speed="12.99"/>
        <vehicle id="always_left.3" lane="1fi_0" pos="190.65" x="190.65" y="498.35" speed="10.73"/>
        <vehicle id="always_left.4" lane="1fi_0" pos="80.07" x="80.07" y="498.35" speed="10.19"/>
        <vehicle id="always_left.5" lane="1fi_0" pos="5.10" x="5.10" y="498.35" speed="0.00"/>
        <vehicle id="always_right.0" lane="3si_0" pos="236.15" x="508.25" y="487.65" speed="0.00"/>
        <vehicle id="always_right.1" lane="3si_0" pos="187.01" x="508.25" y="438.51" speed="13.29"/>
        <vehicle id="always_right.2" lane="3si_0" pos="56.36" x="508.25" y="307.86" speed="13.77"/>
        <vehicle id="always_right.3" lane="3fi_0" pos="187.89" x="501.65" y="187.89" speed="10.57"/>
        <vehicle id="always_right.4" lane="3fi_0" pos="88.22" x="501.65" y="88.22" speed="10.45"/>
        <vehicle id="always_right.5" lane="3fi_0" pos="5.10" x="501.65" y="5.10" speed="0.00"/>
        <vehicle id="horizontal.0" lane="1o_0" pos="41.32" x="447.33" y="501.65" speed="9.84"/>
        <vehicle id="horizontal.1" lane="2si_1" pos="184.50" x="564.00" y="504.95" speed="13.16"/>
        <vehicle id="horizontal.2" lane="2si_1" pos="47.76" x="700.74" y="504.95" speed="12.92"/>
        <vehicle id="horizontal.3" lane="2fi_0" pos="187.16" x="812.84" y="501.65" speed="10.36"/>
        <vehicle id="horizontal.4" lane="2fi_0" pos="89.51" x="910.49" y="501.65" speed="10.42"/>
        <vehicle id="horizontal.5" lane="2fi_0" pos="5.10" x="994.90" y="501.65" speed="0.00"/>
        <vehicle id="vertical.0" lane="3si_1" pos="236.14" x="504.95" y="487.64" speed="0.01"/>
        <vehicle id="vertical.1" lane="3si_1" pos="145.02" x="504.95" y="396.52" speed="13.35"/>
        <vehicle id="vertical.2" lane="3si_1" pos="11.07" x="504.95" y="262.57" speed="11.75"/>
        <vehicle id="vertical.3" lane="3fi_0" pos="154.27" x="501.65" y="154.27" speed="10.69"/>
        <vehicle id="vertical.4" lane="3fi_0" pos="51.21" x="501.65" y="51.21" speed="9.85"/>
    </timestep>
